### ISSUE TITLE
Problem with sampling

### ISSUE THREAD

**Issue by z1433223** [Tobi-r9/RaMViD#13]
Hi @Tobi-r9 , 
I have some questions about sampling. When we were trying to do sampling using command 
`python3.9 scripts/video_sample.py --model_path models/model250000.pt --data_dir data_dir/ --timestep_respacing 25 $MODEL_FLAGS $DIFFUSION_FLAGS`, but it got stuck at `video, _ = next(data)`. We saved a .GIF file under folder 'data_dir' and the pretrained model under folder 'models'. And we are trying to predict a video using your RaMViD model. I will be appreciated if you can help us with this problem.
<img width="510" alt="截屏2023-11-01 13 17 33" src="https://github.com/Tobi-r9/RaMViD/assets/120846601/c129685f-de54-4daa-b66f-fa5ad1a126b6">

**Comment by Tobi-r9** [comment]
Could you let me know where exactly the code stops?

**Comment by z1433223** [comment]
> Could you let me know where exactly the code stops?

Thank you for your prompt response.

To clarify, the code seems to halt or get stuck at the line 84 `video, _ = next(data) `when we execute the video_sample.py script.

**Comment by Tobi-r9** [comment]
Hi, could you let me know which Model Flags you used (specifically the image_size)? Because I cannot reproduce the issue, even with the video you send (I use image_size 64).

**Comment by z1433223** [comment]
I am using commands like this:
```
MODEL_FLAGS="--image_size 64 --num_channels 128 --num_res_blocks 3 --scale_time_dim 0";
DIFFUSION_FLAGS="--diffusion_steps 1000 --noise_schedule linear";
```
`python scripts/video_sample.py --model_path ~/ema_0.9999_500000.pt --data_dir videos/ --timestep_respacing 2 $MODEL_FLAGS $DIFFUSION_FLAGS
`
I seems that `next(data)` did not iterate and it only had one data while generator was running. When I was trying long_sampling, it has the same situation.

**Comment by Tobi-r9** [comment]
Which batch size are you using? If your batch_size is larger than the videos in your data folder, the next(data) will get stuck. If you have one video, but you want to get `n` predictions, you have to set 
```
batch_size=1
num_samples=n
```

**Comment by z1433223** [comment]
Thanks for bringing up this important point!

Here is another question. I had a similar problem as another posted question, which is about missing `from utils.plot import SampleSaver` in long_sampling.py

**Comment by Tobi-r9** [comment]
Hi, sorry for the late response. `SampleSaver` was an old tool I used for analysing the model. I have removed it now and pushed the new version. For me `long_sampling.py` works now with the following command:

```
MODEL_FLAGS="--image_size 64 --num_channels 128 --num_res_blocks 3 --scale_time_dim 0";
DIFFUSION_FLAGS="--diffusion_steps 1000 --noise_schedule linear";
SAMPLE_FLAGS="--cond_generation True --batch_size 1 --num_samples 1 --timestep_respacing 500 --data_dir data/"

python scripts/long_sampling.py --model_path models/ema_0.9999_500000.pt $MODEL_FLAGS $DIFFUSION_FLAGS $SAMPLE_FLAGS
```
It should work for both sampling scripts

**Comment by Tobi-r9** [comment]
Also, I do not think that the model will work properly with `--timestep_respacing 25`, unless you use DDIM sampling maybe.
