### ISSUE TITLE
Regarding Pretrained Model

### ISSUE THREAD

**Issue by LeoXinhaoLee** [Tobi-r9/RaMViD#2]
Hi Tobias, thank you for releasing code for this really inspiring and solid work. From the training detail of your paper, I notice that the overall training time and computation resource needed to train from scratch is relatively large, which is understandable for the nature of the diffusion model. 

Therefore, I'm wondering if it is possible for you to also release some of your trained models, which would be of tremendous help for understanding and applying this method to other potential settings. Thank you.

**Comment by Tobi-r9** [comment]
I am sorry that it took so long, however, we now provide the links to some pre-trained models in the README.
