### ISSUE TITLE
About video sample

### ISSUE THREAD

**Issue by pokameng** [Tobi-r9/RaMViD#3]
Hi
@Tobi-r9 
I am training a new model and the config is follow:

`MODEL_FLAGS="--image_size 64 --num_channels 256 --num_res_blocks 3 --scale_time_dim 0";
DIFFUSION_FLAGS="--diffusion_steps 1000 --noise_schedule linear";
SAMPLE_FLAGS="--batch_size 4 --num_samples 100 --timestep_respacing 1000"

cd /home/dailongquan/110.014/wsm/RaMViD-main
python scripts/video_sample.py --model_path /home/dailongquan/110.014/wsm/RaMViD-main/fanghua_log/openai-2022-12-07-01-11-43-547298/ema_0.9999_016000.pt $MODEL_FLAGS $DIFFUSION_FLAGS $SAMPLE_FLAGS`

But something was wrong with my model:

![image](https://user-images.githubusercontent.com/47957015/206079489-af89ce24-ca91-453f-a4ed-a7312aa32b77.png)
  
![image](https://user-images.githubusercontent.com/47957015/206081185-d22ca52c-8453-4e18-bf22-031ff54b0415.png)

If i set `cond_generation` = True, I must set video_data_dir,right?

**Comment by Tobi-r9** [comment]
Hi @pokameng,

> If i set cond_generation = True, I must set video_data_dir,right?  

Yes, you have to. You get this error because you haven't set `--data_dir`. I hope this helps :).
