### ISSUE TITLE
The disturbed training batch size set

### ISSUE THREAD

**Issue by Costwen** [Tobi-r9/RaMViD#4]
I notice that "When training in a distributed manner, you must manually divide the --batch_size argument by the number of ranks. In lieu of distributed training, you may use --microbatch 16 (or --microbatch 1 in extreme memory-limited cases) to reduce memory usage." In the paper, the batch size is 32, is that each gpu's batch size is 4 when use 8 gpus?

**Comment by Costwen** [comment]
If I want to train on  unconditional ucf101 , the batch size is 64, right?

**Comment by Tobi-r9** [comment]
Yes, both are correct. Thanks for mentioning it, I will add it to the ReadMe.
