### ISSUE TITLE
Model Setting

### ISSUE THREAD

**Issue by hkkkpang** [Tobi-r9/RaMViD#5]
Hi, I have a question regarding your nice work. A task is to use 5 frames to predict next 10 frames. The ground truth of next 10 frames are available. I want to use the ground truth as supervision, in other words, the model should learn to make the predictions to be same as ground truth. It means the model should be deterministic. In this case, does your model work for this task?

**Comment by Tobi-r9** [comment]
This model is not deterministic, i.e. for the same input, it will sample different predictions in each evaluation run. However, if the future is clearly determined by the input frames it still might work
