### ISSUE TITLE
Error: moov atom not found

### ISSUE THREAD

**Issue by ZhouHaoWa** [Tobi-r9/RaMViD#6]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/55025153/209470125-c591cd4c-e3a1-4902-a4d0-2440e5566ba3.png">
i tried about 100step training, then i got the error: "moov atom not found", need i process the video in dataset?    I previously deleted the 0kb size video and videos smaller than 300kb

**Comment by Tobi-r9** [comment]
On which dataset do you get the error? Also, do you get the error on every video or just a few?
