### ISSUE TITLE
how to calculate FVD score on BAIR in your paper?

### ISSUE THREAD

**Issue by JunyaoHu** [Tobi-r9/RaMViD#9]
![image](https://user-images.githubusercontent.com/67564714/232399691-ec1f8685-b38d-49d9-8449-c1c20ab15bdf.png)
![image](https://user-images.githubusercontent.com/67564714/232405106-11b82987-941e-49c9-9fab-a750441cf07f.png)

![image](https://user-images.githubusercontent.com/67564714/232400938-315036db-d557-4268-8c00-2eaa1ae98c14.png)

Hello!  It means you calculate FVD **100 times**, every time you calculate the FVD on **256 video clips**, and every clip has **a length of total16** =cond1+pred15? In MCVD paper the length is total16=cond1+pred15. 

And how to calculate FVD, what is the reference code? I use https://github.com/JunyaoHu/common_metrics_on_video_quality which comes from https://github.com/voletiv/mcvd-pytorch.

My result visualization is as follows, although it looks good, the value is not consistent with your paper. It is about 166. Visualization code is from https://github.com/JunyaoHu/my_common_python_code/blob/main/%E5%8F%AF%E8%A7%86%E5%8C%96/%E8%A7%86%E9%A2%91%E9%A2%84%E6%B5%8B%E7%BB%93%E6%9E%9C%E5%AF%B9%E6%AF%94.py

![save_gif_grid_epoch0_sample](https://user-images.githubusercontent.com/67564714/232407865-8141a8ea-ab29-4771-9a22-2dcf1cc90785.gif)

Hope for your early reply.

**Comment by Tobi-r9** [comment]
Hi, 
we follow https://arxiv.org/abs/2106.13195 for the evaluation procedure on BAIR. As you mentioned correctly, we condition on one frame to predict 15 frames. The FVD is calculated for 256 videos (but it is only calculated for the 15 predicted frames). This is done 100 times and the final FVD is the average of those 100 runs.
We used the original repo to calculate the FVD https://github.com/google-research/google-research/tree/master/frechet_video_distance
I hope this helps, please let me know if there are further issues.

**Comment by JunyaoHu** [comment]
> but it is only calculated for the 15 predicted frames

Hello, I see other paper like [MCVD](https://github.com/voletiv/mcvd-pytorch/issues/19),  [SRVP](https://github.com/edouardelasalles/srvp/blob/3e90a748db04d182290132163fea5b0410ea2452/test.py#L292-L302), [SLAMP](https://github.com/kaanakan/slamp/blob/4f5fc0707a4843d34dd1cb98f4939f1357e05183/calculate_fvd.py#L25-L31) are all add conditional frames into FVD calculation.

**Comment by Tobi-r9** [comment]
Interesting, we did talk to the authors of FitVid and they mentioned that they used only the 15. Nevertheless, the difference seems to be too large (especially since the videos look ok). Did you train a model from scratch or did you use the pre-trained ones?

**Comment by JunyaoHu** [comment]
Hello, thanks for your patience. I used [ema_0.9999_250000](https://1drv.ms/f/s!Amih97wvmSyWgosGv9ekMoXGy_6CSg?e=ElIg3i) in your pre-trained model for BAIR to sample. Since it will spend too much time (1x 3090, batchsize 16, need about 7.7 hours to finish prediction), we only do a calculation every time. 

Since https://github.com/Tobi-r9/RaMViD/issues/9#issue-1670496944 only use **250 steps** to sample, this time I use **1000 step** to sample for aligning the configuration.

Our run script is as follows:
```
MODEL_FLAGS="--image_size 64 --num_channels 128 --num_res_blocks 2 --scale_time_dim 0";
DIFFUSION_FLAGS="--diffusion_steps 1000 --noise_schedule linear";
python scripts/video_sample.py \
    --batch_size 16 \
    --num_samples 256 \
    --seq_len 16 \
    --cond_frames "0," \
    --data_dir /mnt/sda/hjy/bair/ramvid_processed \
    --model_path /mnt/sda/hjy/ramvid_checkpoints/ema_0.9999_250000.pt \
    $MODEL_FLAGS \
    $DIFFUSION_FLAGS
```

Visualization calculation result is:
![save_gif_grid_epoch0_sample_1cond15pred](https://user-images.githubusercontent.com/67564714/233517298-32524470-4dcc-4021-9618-83a74c2d8329.gif)

Our result is:
```
fvd    159.08139629141363       # len = 16 = 1+15
fvd    142.0408683335384        # len = 15
ssim   0.7473556877632316
psnr   17.156869397981314
lpips  0.08816499882462571
elapsed time: 27823.748425006866
```

And I can provide my predicted result file [video1.pt and video2.pt](https://drive.google.com/drive/folders/1DYqKEqoUst69LL2RmB91zS9JNjBkf8i3?usp=sharing). 
- video1 (ground truth with conditional frames, `b=256 t=16=1+15 c h w`) 
- video2 (predicted result with conditional frames, `b=256 t=16=1+15 c h w`)

**Comment by Tobi-r9** [comment]
For your FVD library it says 

> ps: pixel value should be in [0, 1]!  

Did you account for that? 
Also just to be sure, you do calculate the FVD on all 256 videos together and not just on small batches and build the average?

**Comment by JunyaoHu** [comment]
Hi, author, thanks for your question. 

---

Q1: Did you account for `pixel value should be in [0, 1]`

A1: Because I use the repo of MCVD, and I follow their work. The code requires the input video should be in [0,1], [here](https://github.com/voletiv/mcvd-pytorch/blob/451da2eb635bad50da6a7c03b443a34c6eb08b3a/models/fvd/fvd.py#L52-L56). By `‎preprocess_single` the video will be scaled to [-1,1] and (224,224) which is the same as original FVD calculation method.

![image](https://user-images.githubusercontent.com/67564714/233759217-ca26425f-9ebe-4fe1-8d44-bdf914aa3a41.png)
![image](https://user-images.githubusercontent.com/67564714/233759242-09389412-b277-461a-bc42-375eb1af65f8.png)
![image](https://user-images.githubusercontent.com/67564714/233759094-a05cbca1-bd46-4d93-aec4-0ca1e1e8a6a6.png)

And for fair comparison, I will try to calculate FVD using google original method later.

---

Q2: You do calculate the FVD on all 256 videos together and not just on small batches and build the average?

A2: For memory limit, we predict in minibatch such as [16,t,c,h,w] and save them temporarily, we do this process 256/16=16 times, then we concat these temporary tensor into a big batch [256,t,c,h,w], and we calculate FVD of batch [256,t,c,h,w].

**Comment by JunyaoHu** [comment]
![image](https://user-images.githubusercontent.com/67564714/233771991-452e5910-b4dd-452e-aa44-1facf4b20fc4.png)

I see you compare with MCVD so I think you had better to choose their method. But now the method of calculating fvd is different for each model, so I feel confused.

**Comment by Tobi-r9** [comment]
About Q1: 
Yes, but RaMViD saves videos in [0,255] range. So do you rescale to [0,1] before you run the MCVD code?
About Q2:
That seems fine, I did it the same way. 

I don't know if this helps, but we actually at some point used https://github.com/wilson1yan/VideoGPT to calculate the FVD and that gave us the same results. Maybe you can check this one as well?

**Comment by JunyaoHu** [comment]
About Q1:
Yes.

OK, I will try to use https://github.com/wilson1yan/VideoGPT for check.

Thank you for your patience! Good luck with your research  : )
